apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - api-deployment.yml
  - api-service.yml
  - web-deployment.yml
  - web-service.yml
  - ingress.yml
namespace: webapp
commonLabels:
  app: webapp
